/* Ambient declarations for everything the sandbox puts in scope.
   This is what turns "a textarea" into autocomplete, hover docs and signature
   help. The doc comments matter as much as the signatures — they are the API
   reference the lab never has to render as a separate page. */

export const SANDBOX_TYPES = [
  'declare namespace JSX { interface IntrinsicElements { [tag: string]: any } }',
  '',
  '/** One OCR extraction job. */',
  'interface OcrJob {',
  '  /** Job id, e.g. "job_1002". */',
  '  id: string;',
  '  /** Original filename, e.g. "invoice-4417.pdf". */',
  '  file: string;',
  '  /** queued -> processing -> done, or failed. */',
  '  status: "queued" | "processing" | "done" | "failed";',
  '  /** Page count of the document. */',
  '  pages: number;',
  '  /** Extraction progress, 0-100. */',
  '  progress: number;',
  '  /** OCR confidence 0-1. Null until the job is done. */',
  '  confidence: number | null;',
  '  createdAt: number;',
  '}',
  '',
  '/** The fake backend. setTimeout only - there is no network. */',
  'declare const mockApi: {',
  '  /** Every job in the queue. Rejects about 20% of the time with a 503. */',
  '  listJobs(): Promise<OcrJob[]>;',
  '  /** One job by id. Each read advances a processing job ~25%, so polling converges on "done". Never fails. */',
  '  getJob(id: string): Promise<OcrJob>;',
  '  /** Uploads a document and returns the created job. Rejects about 20% of the time. */',
  '  uploadDocument(input: { file: string }): Promise<OcrJob>;',
  '  /** Re-queues a failed job. Rejects about 20% of the time. */',
  '  retryJob(id: string): Promise<OcrJob>;',
  '  /** Starts a fresh long job that needs 4-5 polls to finish. Never fails. */',
  '  startExtraction(name?: string): Promise<OcrJob>;',
  '  /** Restores the seed data. */',
  '  reset(): void;',
  '};',
  '',
  '/** Writes a line to the sandbox log under the preview. Survives unmount, which is how you see a leaked timer. */',
  'declare function log(message: any): void;',
  '',
  '/** Returns how many times this component has rendered. Uses a ref, so it never causes a render itself. */',
  'declare function useRenderCount(): number;',
  '',
  '// ---- React -------------------------------------------------------------',
  '',
  '/** State that survives re-renders. Use the updater form when the next value depends on the previous one. */',
  'declare function useState<S>(initial: S | (() => S)): [S, (next: S | ((prev: S) => S)) => void];',
  '/** Synchronises with something outside React. Return a cleanup function. Omit deps and it runs after every render. */',
  'declare function useEffect(effect: () => (void | (() => void)), deps?: ReadonlyArray<any>): void;',
  'declare function useLayoutEffect(effect: () => (void | (() => void)), deps?: ReadonlyArray<any>): void;',
  '/** A mutable box that survives renders and never causes one. */',
  'declare function useRef<T>(initial: T): { current: T };',
  '/** Caches a computed value between renders while deps are unchanged. */',
  'declare function useMemo<T>(factory: () => T, deps: ReadonlyArray<any>): T;',
  '/** Keeps a function identity stable between renders. */',
  'declare function useCallback<T>(fn: T, deps: ReadonlyArray<any>): T;',
  '/** Reads the nearest Provider value. Re-renders this component whenever that value changes identity. */',
  'declare function useContext<T>(context: LabContext<T>): T;',
  '/** State transitions as a pure function. dispatch(action) never goes stale the way a captured value does. */',
  'declare function useReducer<S, A>(reducer: (state: S, action: A) => S, initial: S): [S, (action: A) => void];',
  'declare function useSyncExternalStore<T>(subscribe: (cb: () => void) => () => void, getSnapshot: () => T): T;',
  '/** A stable unique id, safe across server and client. For htmlFor/aria wiring - never as a list key. */',
  'declare function useId(): string;',
  'declare function useImperativeHandle<T>(ref: any, create: () => T, deps?: ReadonlyArray<any>): void;',
  '/** [isPending, startTransition]. Work started inside the callback is interruptible, so typing stays responsive. */',
  'declare function useTransition(): [boolean, (callback: () => void) => void];',
  '/** Returns a copy of the value that lags behind during urgent updates. The cheap way to keep an expensive list from blocking input. */',
  'declare function useDeferredValue<T>(value: T): T;',
  'declare function startTransition(callback: () => void): void;',
  '/** Lets a parent hold a ref to a child DOM node. */',
  'declare function forwardRef<T>(render: T): T;',
  'declare const Suspense: any;',
  '',
  'interface LabContext<T> { Provider: any; Consumer: any; displayName?: string; }',
  '/** Creates a context channel. The default value is used when there is no Provider above. */',
  'declare function createContext<T>(defaultValue: T): LabContext<T>;',
  '/** Skips a re-render when props are shallow-equal. Does NOT block context updates. */',
  'declare function memo<T>(component: T): T;',
  'declare const React: any;',
  'declare const Fragment: any;',
  '',
  '// ---- zustand -----------------------------------------------------------',
  '',
  'interface LabStore<T> {',
  '  /** Subscribes to the WHOLE store - re-renders on every change. Prefer a selector. */',
  '  (): T;',
  '  /** Subscribes to one slice. Re-renders only when that slice changes by Object.is. */',
  '  <U>(selector: (state: T) => U): U;',
  '  /** Reads current state without subscribing. Use this inside event handlers. */',
  '  getState(): T;',
  '  setState(partial: Partial<T> | ((state: T) => Partial<T>)): void;',
  '  subscribe(listener: (state: T, previous: T) => void): () => void;',
  '}',
  '/** Creates a store outside React. No provider needed. */',
  'declare function create<T>(',
  '  initializer: (',
  '    set: (partial: Partial<T> | ((state: T) => Partial<T>)) => void,',
  '    get: () => T',
  '  ) => T',
  '): LabStore<T>;',
  '/** Wraps a selector that returns a new object or array so it is compared key by key instead of by reference. */',
  'declare function useShallow<S, U>(selector: (state: S) => U): (state: S) => U;',
  '',
  '// ---- React Query -------------------------------------------------------',
  '',
  'interface LabQueryResult<T> {',
  '  data: T;',
  '  error: any;',
  '  /** No data yet. This is the first-load branch. */',
  '  isPending: boolean;',
  '  /** A request is in flight, including a background refetch while data is on screen. */',
  '  isFetching: boolean;',
  '  /** isPending && isFetching. */',
  '  isLoading: boolean;',
  '  isError: boolean;',
  '  isSuccess: boolean;',
  '  status: "pending" | "error" | "success";',
  '  fetchStatus: "fetching" | "paused" | "idle";',
  '  failureCount: number;',
  '  dataUpdatedAt: number;',
  '  refetch(): Promise<any>;',
  '}',
  'interface LabQueryOptions<T> {',
  '  /** Cache identity. ["jobs"] and ["job", id] are different entries; this is also what you invalidate by. */',
  '  queryKey: ReadonlyArray<any>;',
  '  /** Returns a promise. Throw or reject to land in the error state. */',
  '  queryFn: (context?: any) => Promise<T>;',
  '  /** While false the query does not run at all. Use it to wait for an id. */',
  '  enabled?: boolean;',
  '  /** How long data counts as fresh, in ms. 0 by default, so it refetches in the background. */',
  '  staleTime?: number;',
  '  /** How long an unused cache entry is kept, in ms. Renamed from cacheTime in v5. */',
  '  gcTime?: number;',
  '  /** A number polls forever. A function (query) => number | false can stop itself. */',
  '  refetchInterval?: number | false | ((query: any) => number | false);',
  '  refetchOnWindowFocus?: boolean;',
  '  retry?: number | boolean;',
  '  retryDelay?: number | ((attempt: number) => number);',
  '  /** Transform the cached data for this component only. */',
  '  select?: (data: any) => any;',
  '  /** Pass keepPreviousData to keep the old page on screen while a new key loads. */',
  '  placeholderData?: any;',
  '  initialData?: T;',
  '}',
  '/** Reads server state: cache, dedupe, retry, background refetch, loading and error flags. */',
  'declare function useQuery<T = any>(options: LabQueryOptions<T>): LabQueryResult<T>;',
  '',
  'interface LabMutationResult<TData, TVars> {',
  '  /** Fires the mutation. Fire and forget. */',
  '  mutate(variables?: TVars): void;',
  '  /** Fires the mutation and gives you a promise to await. */',
  '  mutateAsync(variables?: TVars): Promise<TData>;',
  '  data: TData;',
  '  error: any;',
  '  /** The write is in flight. Disable the button with this. */',
  '  isPending: boolean;',
  '  isError: boolean;',
  '  isSuccess: boolean;',
  '  isIdle: boolean;',
  '  reset(): void;',
  '}',
  'interface LabMutationOptions<TData, TVars> {',
  '  /** Performs the write and returns a promise. */',
  '  mutationFn: (variables: TVars) => Promise<TData>;',
  '  /** Where invalidateQueries belongs. */',
  '  onSuccess?: (data: TData, variables: TVars) => void;',
  '  onError?: (error: any, variables: TVars) => void;',
  '  onSettled?: (data: TData, error: any, variables: TVars) => void;',
  '  /** Runs before the request. Return a context value for optimistic rollback. */',
  '  onMutate?: (variables: TVars) => any;',
  '}',
  '/** Writes to the server. Does not touch the cache by itself - invalidate in onSuccess. */',
  'declare function useMutation<TData = any, TVars = any>(options: LabMutationOptions<TData, TVars>): LabMutationResult<TData, TVars>;',
  '',
  'interface LabQueryClient {',
  '  /** Marks matching queries stale so they refetch. The v5 signature takes a filters object. */',
  '  invalidateQueries(filters: { queryKey?: ReadonlyArray<any>; exact?: boolean }): Promise<void>;',
  '  getQueryData(queryKey: ReadonlyArray<any>): any;',
  '  setQueryData(queryKey: ReadonlyArray<any>, updater: any): void;',
  '  cancelQueries(filters: { queryKey?: ReadonlyArray<any> }): Promise<void>;',
  '  removeQueries(filters: { queryKey?: ReadonlyArray<any> }): void;',
  '}',
  '/** Reaches the client the lab already mounted around your component. */',
  'declare function useQueryClient(): LabQueryClient;',
  'declare function useQueries(options: any): any[];',
  'declare const QueryClient: any;',
  'declare const QueryClientProvider: any;',
  '/** placeholderData: keepPreviousData - keeps the previous page visible while a new key loads. */',
  'declare const keepPreviousData: any;',
  '',
  '// ---- React Router ------------------------------------------------------',
  '',
  '/** Keeps history in memory instead of the address bar. The lab uses this so your routes cannot hijack the page URL. */',
  'declare const MemoryRouter: any;',
  '/** Picks the single best matching Route below it. */',
  'declare const Routes: any;',
  '/** path="jobs/:id" - a leading : marks a param. index replaces path for the default child. */',
  'declare const Route: any;',
  '/** Declarative navigation. Renders an anchor and never reloads the page. */',
  'declare const Link: any;',
  '/** Link that knows whether it is active: className can be a function of { isActive }. */',
  'declare const NavLink: any;',
  '/** Where a parent route renders its matched child. Nested layouts need this. */',
  'declare const Outlet: any;',
  '/** Redirects on render. Pass replace so the bad URL does not stay in history. */',
  'declare const Navigate: any;',
  '',
  '/** Imperative navigation, for after an action completes. navigate(-1) goes back. */',
  'declare function useNavigate(): (to: string | number, options?: { replace?: boolean; state?: any }) => void;',
  '/** The :params matched from the current URL. Always strings. */',
  'declare function useParams(): Record<string, string>;',
  '/** { pathname, search, hash, state, key } for the current location. */',
  'declare function useLocation(): { pathname: string; search: string; hash: string; state: any; key: string };',
  '/** The query string as state. Read with get(name); set with the second element, which navigates. */',
  'declare function useSearchParams(): [URLSearchParams, (next: any, options?: { replace?: boolean }) => void];',
  'declare function useMatch(pattern: string): any;',
  '',
  '// ---- display helpers, already styled for you ---------------------------',
  '',
  '/** Status chip: queued / processing / done / failed. */',
  'declare function StatusPill(props: { status: string }): any;',
  '/** A clickable job row with filename, id, page count and status. */',
  'declare function JobRow(props: { job: OcrJob; selected?: boolean; onClick?: () => void }): any;',
  '/** A titled card. Pass count to show a render-counter badge. */',
  'declare function Panel(props: { title: any; count?: number; children?: any }): any;',
  'declare function Spinner(props?: { className?: string }): any;',
  'declare function RenderBadge(props: { count: number }): any;'
].join('\n');
